# -*- coding: utf-8 -*-
"""spark retail df.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCqrGKAs0UZmKhN4orlzl3IjC9bF_SZf
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import sum,col
spark=SparkSession.builder.appName('online retail session').getOrCreate()
df=spark.read.csv('/content/online_retail.csv',header=True,inferSchema=True)
df.show()

df.select('Country').distinct().count()

df.columns

df.printSchema()

from pyspark.sql import Window
import pyspark.sql.functions as F

w = Window.partitionBy("Country").orderBy(F.rand())
sample_df = df.withColumn("row_num", F.row_number().over(w)) \
              .filter(F.col("row_num") <= 500) \
              .drop("row_num")

print(sample_df.count())

sample_df.select('Country').distinct().count()

sample_df=sample_df.drop('InvoiceNo','CustomerID','Description')

sample_df = sample_df.filter(sample_df.Quantity > 0)

from pyspark.sql.functions import month, dayofweek, hour

sample_df = sample_df.withColumn("InvoiceMonth", month("InvoiceDate")) \
       .withColumn("InvoiceWeekDay", dayofweek("InvoiceDate")) \
       .withColumn("InvoiceHour", hour("InvoiceDate"))
sample_df=sample_df.drop('InvoiceDate')
sample_df.show()

sample_df.select([sum(col(c).isNull().cast("int")).alias(c) for c in sample_df.columns]).show()

## do some sql
sample_df.createOrReplaceTempView("retail")
sample_df = spark.sql("""
SELECT *,
       CASE WHEN UnitPrice > 50 THEN 1 ELSE 0 END AS HighPriceFlag,
       CASE WHEN UnitPrice < 5 THEN 1 ELSE 0 END AS LowPriceFlag,
       CASE WHEN InvoiceWeekDay IN (6,7) THEN 1 ELSE 0 END AS IsWeekend,
       CASE WHEN InvoiceHour < 12 THEN 1 ELSE 0 END AS IsMorning,
       CASE WHEN InvoiceHour >= 18 THEN 1 ELSE 0 END AS IsEvening


FROM retail
""")
sample_df.show(5)
sample_df.printSchema()

# encode  country
sample_df=sample_df.drop('StockCode')
sample_df.show()

from pyspark.ml.feature import StringIndexer

country_indexer = StringIndexer(
    inputCol="Country",
    outputCol="CountryIndex",
    handleInvalid="keep"
)

sample_df = country_indexer.fit(sample_df).transform(sample_df)
sample_df=sample_df.drop('Country')

# ML traininng 
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import RandomForestRegressor
from pyspark.ml.evaluation import RegressionEvaluator


target_col = "Quantity"

feature_cols = [c for c in sample_df.columns if c != target_col]

print("Features used:")
print(feature_cols)

#  Vector Assembler
assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features"
)

sample_df_vec = (
    assembler
    .transform(sample_df)
    .select("features", target_col)
)


train_df, test_df = sample_df_vec.randomSplit([0.8, 0.2], seed=42)

rf = RandomForestRegressor(
    featuresCol="features",
    labelCol=target_col,
    numTrees=100,
    maxDepth=8,
    maxBins=40,
    seed=42
)

rf_model = rf.fit(train_df)


predictions = rf_model.transform(test_df)


evaluator = RegressionEvaluator(
    labelCol=target_col,
    predictionCol="prediction",
    metricName="rmse"
)

rmse = evaluator.evaluate(predictions)

r2_evaluator = RegressionEvaluator(
    labelCol=target_col,
    predictionCol="prediction",
    metricName="r2"
)

r2 = r2_evaluator.evaluate(predictions)

print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.3f}")

pred_pd = predictions.select("prediction", target_col).toPandas()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid", palette="muted")

plt.figure(figsize=(8,6))

sns.scatterplot(
    x=target_col,
    y="prediction",
    data=pred_pd,
    hue="prediction",
    palette="viridis",
    alpha=0.7,
    s=60
)
max_val = max(pred_pd[target_col].max(), pred_pd["prediction"].max())
plt.plot([0, max_val], [0, max_val], color="red", linestyle="--", linewidth=2)

plt.xlabel("Actual Quantity", fontsize=12)
plt.ylabel("Predicted Quantity", fontsize=12)
plt.title("Actual vs Predicted Quantity (RF Model)", fontsize=14)
plt.legend(title="Prediction")
plt.tight_layout()
plt.show()

residuals_pd = predictions.select("prediction", target_col).toPandas()
residuals_pd["residual"] = residuals_pd[target_col] - residuals_pd["prediction"]

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid", palette="muted")

plt.figure(figsize=(8,6))

sns.scatterplot(
    x="prediction",
    y="residual",
    data=residuals_pd,
    hue="residual",
    palette="coolwarm",
    alpha=0.7,
    s=60
)

plt.axhline(0, color="black", linestyle="--", linewidth=2)

plt.xlabel("Predicted Quantity", fontsize=12)
plt.ylabel("Residual (Actual - Predicted)", fontsize=12)
plt.title("Residual Plot (RF Model)", fontsize=14)
plt.legend(title="Residual")
plt.tight_layout()

plt.show()